data:
  Chipotle:
    source: 'direct-download'
    data-src-path: 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
  Occupation:
    source: 'direct-download'
    data-src-path: 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
  World-Food-Facts:
    source: 'kaggle-datasets'
    data-src-path: 'openfoodfacts/world-food-facts'
    

outputs:
  Chipotle:
    nb-html-preview: 'true'
    py-percent-script: 'true'
    output-path: 'pandas-exercises/Getting to know the data/Chipotle'
  Occupation:
    nb-html-preview: 'true'
    py-percent-script: 'true'
    output-path: 'pandas-exercises/Getting to know the data/Occupation'
  World-Food-Facts:
    nb-html-preview: 'true'
    py-percent-script: 'true'
    output-path: 'pandas-exercises/Getting to know the data/World Food Facts'

  

